// This file is autogenerated. Do not modify.

#ifndef TICKET_RUN_H_
#define TICKET_RUN_H_

#include "parser.h"
#include "result.h"
#include "response.h"

namespace ticket::command {

/**
 * @brief Visitor for the commands.
 *
 * The main function uses this visitor after parsing a
 * command, to actually dispatch it. Overloads of operator()
 * are callbacks of the commands.
 *
 * The implementations are in the corresponding source
 * files, not in run.cpp.
 */
auto run (const AddUser &cmd) -> Result<Response, Exception>;
auto run (const Login &cmd) -> Result<Response, Exception>;
auto run (const Logout &cmd) -> Result<Response, Exception>;
auto run (const QueryProfile &cmd) -> Result<Response, Exception>;
auto run (const ModifyProfile &cmd) -> Result<Response, Exception>;
auto run (const AddTrain &cmd) -> Result<Response, Exception>;
auto run (const DeleteTrain &cmd) -> Result<Response, Exception>;
auto run (const ReleaseTrain &cmd) -> Result<Response, Exception>;
auto run (const QueryTrain &cmd) -> Result<Response, Exception>;
auto run (const QueryTicket &cmd) -> Result<Response, Exception>;
auto run (const QueryTransfer &cmd) -> Result<Response, Exception>;
auto run (const BuyTicket &cmd) -> Result<Response, Exception>;
auto run (const QueryOrder &cmd) -> Result<Response, Exception>;
auto run (const RefundTicket &cmd) -> Result<Response, Exception>;
auto run (const Rollback &cmd) -> Result<Response, Exception>;
auto run (const Clean &cmd) -> Result<Response, Exception>;
auto run (const Exit &cmd) -> Result<Response, Exception>;

} // namespace ticket::command

#endif // TICKET_RUN_H_
